name: Nightly build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get . && go get github.com/mitchellh/gox && go install github.com/mitchellh/gox@latest && gox -h
      - name: Cross-compile with go
        run: cd ./cmd/zgrab2 && gox -os='!darwin'
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: ./cmd/zgrab2/zgrab2_*
